import type { CanonicalFood } from './types';
import { SEED_FOODS } from './seedFoods';
import recipeCofidFoods from '../generated/cofid/recipeFoods.json';

/**
 * The local canonical food store. Holds reviewed foods that ship with the app so
 * saved recipes calculate offline with NO network. Today this is the manual
 * reviewed seed; once `scripts/import-cofid.ts` runs against the official CoFID
 * spreadsheet, the generated `src/data/generated/cofid/foods.json` records merge
 * here (CoFID verified-primary supersedes a manual record with the same alias).
 *
 * External providers (FDC, Open Food Facts) are NEVER merged into this shipped
 * store — FDC is optional enrichment and Open Food Facts is ODbL (share-alike),
 * fetched at runtime only.
 */

/**
 * Bundled CoFID records referenced by reviewed recipe links (small — generated by
 * `scripts/extract-recipe-foods.ts`). The FULL 2,886-record CoFID dataset stays
 * OUT of the main bundle and is lazy-loaded on demand by the CoFID provider for
 * food search (see providers/cofidLocal.ts). Verified-primary CoFID records are
 * spread BEFORE the manual seed so they win on id/alias collisions.
 */
const generatedCofid = recipeCofidFoods as unknown as CanonicalFood[];

export const ALL_LOCAL_FOODS: CanonicalFood[] = [...generatedCofid, ...SEED_FOODS];

const BY_ID = new Map<string, CanonicalFood>(ALL_LOCAL_FOODS.map((f) => [f.id, f]));

export function getLocalFood(id: string): CanonicalFood | undefined {
  return BY_ID.get(id);
}

export function allLocalFoods(): CanonicalFood[] {
  return ALL_LOCAL_FOODS;
}

function tokens(s: string): string[] {
  return s.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean);
}

/** Simple relevance score 0–1 for a text query against a food. Punctuation-robust
 *  (CoFID names use commas, e.g. "Salmon, farmed, flesh only, grilled"). */
export function scoreFood(food: CanonicalFood, text: string): number {
  const q = text.trim().toLowerCase();
  if (!q) return 0;
  const name = food.canonicalName.toLowerCase();
  const display = food.displayName.toLowerCase();
  if (name === q || display === q) return 1;
  if (food.aliases.some((a) => a.toLowerCase() === q)) return 0.95;
  if (name.startsWith(q) || display.startsWith(q)) return 0.9;
  if (name.includes(q) || display.includes(q)) return 0.8;
  if (food.aliases.some((a) => a.toLowerCase().includes(q))) return 0.65;
  // Token overlap (fraction of query tokens present), robust to punctuation.
  const qTokens = tokens(q);
  const nTokens = new Set([...tokens(name), ...food.aliases.flatMap(tokens)]);
  const matched = qTokens.filter((t) => nTokens.has(t)).length;
  if (matched === 0) return 0;
  return 0.3 + 0.45 * (matched / qTokens.length); // all query tokens present → 0.75
}
